zsgi_data:
  image: busybox
  volumes:
    - /var/lib/mysql
  command: "true"

zsgi_db:
  image: mariadb
  environment:
    MYSQL_DATABASE: zweb
    MYSQL_USER: zille
    DATABASE_PASSWORD: zille123
    MYSQL_ROOT_PASSWORD: zille123 
  ports:
    - "3306:3306"
  volumes_from:
    - zsgi_data 

